# -*- coding: utf-8 -*-
"""Posee.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Q4TGRY0gNdyYyEm-SFoJS1aRwHer2Qm

**Proyecto Final: Unidad 1**

**Entidad: Posee**

(Esta acción se convirtió en una entidad porque hay relación de n a n)
"""

#Faker es un paquete de Python que genera datos falsos.
!pip install Faker

#Librerías necesarias para la generación de datos.
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

#Variable asignada para el tamaño del conjunto de datos. 
num_iess = 10000

#Lista de 2 características (Atributos)
features = [
    "id_perfil",
    "id_usuario",
]# Creando un DF para estas características
df = pd.DataFrame(columns=features)

"""**id_perfil**"""

#Biblioteca uuid para generar cadena aleatoria de datos para id_perfil.
df['id_perfil'] = [uuid.uuid4().hex for i in range(num_iess)]

#Genera identificaciones únicas para cada usuario. Si todas las ID en el conjunto de datos son únicas, devuelve True.
print(df['id_perfil'].nunique()==num_iess)

"""**id_usuario**"""

#Biblioteca uuid para generar cadena aleatoria de datos para id_perfil.
df['id_usuario'] = [uuid.uuid4().hex for i in range(num_iess)]

#Genera identificaciones únicas para cada usuario. Si todas las ID en el conjunto de datos son únicas, devuelve True.
print(df['id_usuario'].nunique()==num_iess)

#Visualizar en la tabla los datos generados antes de descargar el excel.
df.head(5)

#Generar excel de los datos.
df.to_csv('posee.csv')